### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by misterhtmlcss** [sar-gupta/space#5]
Clicked on the Github login and it won't allow a login. Also regardless it's frustrating that your demo app is asking me to login; seems pretty odd and sketchy.

**Comment by sar-gupta** [comment]
Hey, login *needs* to be implemented as one of the basic functionality of a chat app.

 It's working fine for a lot of other people.

Can you share the devtools console output when you login?

**Comment by misterhtmlcss** [comment]
Yeah I could, but I won't return. I know you believe you need to make it login as the 'basic' functionality, but then how does Gitter, Spectrum all manage to function without requiring a login to view the app. I'm not logging in against, I still feel filthy from the first time.

Good luck though!
