### ISSUE TITLE
name issue

### ISSUE THREAD

**Issue by Getinwiththem** [sar-gupta/space#6]
the reason youre not able to display the name from firebase is because the syntax is wrong.It should be username instead of name...cheers!

**Comment by sar-gupta** [comment]
Hey @Getinwiththem 
I'm setting the name here: https://github.com/sar-gupta/space/blob/49e012b70f104dc2f0bfffc8756357ec1b5e33b2/src/actions/auth.js#L18

I'm using `user.displayName` to get the name from the signed in user information, as you can see in the code linked above. Could you be more specific where you found the problem in the code? (It'd be great if you could provide the permalink to the line of code)

**Comment by sar-gupta** [comment]
Closing due to no response.
